name = "bx-app-quotation-generator"
main = "src/index.js"
compatibility_date = "2025-08-31"

# KV Storage for Bitrix24 auth data
[[kv_namespaces]]
binding = "BITRIX_KV"
id = "f6a4d0e328454bf989e51003978b9c4d"

# Environment variables
[vars]
APP_NAME = "Bitrix24 Quotation Generator"

# Use Workers dev domain (remove routes to avoid conflicts)
workers_dev = true